python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS1770145 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0360121 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0370221 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS3600186 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0370172 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0360218 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0160485 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0160466 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS9410517 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0360520 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0070243 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS3600361 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0070120 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS1770310 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS3600671 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/mri/ -mri

python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS1770145 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0360121 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0370221 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS3600186 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0370172 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0360218 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0160485 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0160466 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS9410517 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0360520 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0070243 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS3600361 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0070120 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS1770310 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS3600671 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/fbb/ -fbb

python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS1770145 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0360121 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0370221 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS3600186 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0370172 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0360218 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0160485 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0160466 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS9410517 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0360520 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0070243 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS3600361 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS0070120 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS1770310 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
python /home/mac/pmaiti/Desktop/leads_qc/rablabqc/leadsqc.py /mnt/coredata/processing/leads/data/processed/LDS3600671 /shared/petcore/Projects/LEADS/data_f7p1/summary/piyush_qc/ftp/ -ftp
